[package]
name = "latticeLadder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
num-bigint = "0.4.3"
glass_pumpkin = "1.5.0"
rand ="0.8.5"
